package entities.Stocks

import entities.Entity

case class Company(id: String,
                   created: String,
                   logo:String,
                   listdate: String,
                   cik:String,
                   bloomberg: String,
                   figi: String,
                   lei: String,
                   sic: Int,
                   country: String,
                   industry: String,
                   sector: String,
                   marketcap: Int,
                   employees: Int,
                   phone: String,
                   ceo: String,
                   url: String,
                   description: String,
                   exchange: String,
                   name: String,
                   symbol: String,
                   exchangeSymbol: String,
                   hq_address:String,
                   hq_state: String,
                   hq_country: String,
                   typeOf: String,
                   updated: String,
                   tags: Seq[String],
                   similar: Seq[String],
                   active: Boolean) extends Entity
